spring.main.web-application-type: none

chrome-driver-executable-path: 'C:\Selenium\chromedriver.exe'
headless: false

telegram-bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: futjitsu_bot
  chat-it: ${TELEGRAM_BOT_CHAT_ID}
