spring.main.web-application-type: none

chrome-driver-executable-path: '/usr/local/bin/chromedriver'
headless: false

telegram-bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: futjitsu_bot
  chat-it: ${TELEGRAM_BOT_CHAT_ID}
