spring.main:
  web-application-type: none
  allow-circular-references: true

platform: PC
chrome-driver-executable-path: '/usr/local/bin/chromedriver'
chrome-user-data-dir: 'selenium'

telegram-bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: futjitsu_bot

bidder:
  min-player-price-for-mass-bidder: 1500
  max-player-price-for-mass-bidder: 25000
  max-expiration-time: 15m
  max-active-bids-per-player: 5
  min-expected-profit: 300
  extra-margin-when-listing: 100

futbin:
  min-time-between-requests: 20m
  bidding-squad-urls: https://www.futbin.com/24/squad/1455593,
                      https://www.futbin.com/24/squad/1455544,
                      https://www.futbin.com/24/squad/1455447,
                      https://www.futbin.com/24/squad/1455486
  deduplication-map: #futbin-id --> extended name
    2522: 'Gabriel Jesus'
    2520: 'Luis Diaz'
    83: 'Reece James'
    107: 'Chloe Kelly'
    150: 'Cristiano Ronaldo'
