spring.main:
  web-application-type: none
  allow-circular-references: true

platform: PC
chrome-driver-executable-path: '/usr/local/bin/chromedriver'
chrome-user-data-dir: 'selenium'

telegram-bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: futjitsu_bot
