server:
  port: 8081

platform: PC
chrome-driver-executable-path: '/usr/local/bin/chromedriver'
chrome-user-data-dir: 'selenium'

telegram-bot:
  token: ${TELEGRAM_BOT_TOKEN}
  username: futjitsu_bot

spring:
  main:
    web-application-type: none
    allow-circular-references: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: "fut_selenium"
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      telegram-bot-commands:
        name: "telegram_bot_commands"

futbin:
  deduplication-map: #futbin-id --> extended name
    26786: 'Gabriel Jesus'
    26352: 'Luis Diaz'
    26344: 'Reece James'
    26777: 'Alejandro Gomez'
    26422: 'Lucas Hernandez'
    26339: 'Thiago Silva'
    26304: 'Edouard Mendy'